version: '3.8'

services:
  drupal_db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/mysql
      - /var/jenkins_home/sql_backups:/sql  # 👈 Mount SQL backup folder from Jenkins

  drupal_web:
    image: drupal:11-php8.3-apache
    ports:
      - "8090:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - drupal_db

volumes:
  db_data:

