version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: drupal_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: drupal:11-php8.3-apache
    container_name: drupal_web
    ports:
      - "8090:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
    environment:
      # Optional but good practice:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
      - PHP_OPCACHE_REVALIDATE_FREQ=0

volumes:
  db_data:
